#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x gnome-keyring-daemon > /dev/null || gnome-keyring-daemon --start --components=secrets &
sh ~/.fehbg
pgrep -x picom > /dev/null || picom &
pgrep -x flameshot > /dev/null || flameshot &
pgrep -x nm-applet > /dev/null || nm-applet &
pgrep -x polybar > /dev/null || /bin/sh -c ~/.config/polybar/launch.sh
sh ~/.local/bin/startup & disown
xset r rate 300 50

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# Appearance
bspc config border_width        3
bspc config window_gap          20
bspc config top_padding		25
bspc config bottom_padding	0
bspc config left_padding	0
bspc config right_padding	0
bspc config split_ratio		0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config automatic_scheme 	alternate
# Window
bspc config pointer_modifier shift
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Rules
bspc rule -a 'Brave-browser' border=off
bspc rule -a 'discord' border=off
bspc rule -a 'tabbed' border_width=1
bspc rule -a 'Termite' border_width=1

