#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x gnome-keyring-daemon > /dev/null || gnome-keyring-daemon &
sh ~/.fehbg
picom &
pgrep -x nm-applet > /dev/null || nm-applet &
pgrep -x polybar > /dev/null || /bin/sh -c ~/.config/polybar/launch.sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width        4
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a zoom state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
